version: '3'
services: 

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        hostname: mongodb    

    tweet_collector:
        build: tweet_collector/
        volumes: 
        - ./tweet_collector/:/app
        depends_on: 
        - mongodb 
           
       
    pgdb:
        image: postgres
        ports:  
        - "5556:5432"
        environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
        restart: always
        hostname: pgdb 
        
    etl:
        build: etl/
        volumes:
        - ./etl/:/app
        depends_on:
        - mongodb
        - pgdb
       
        
    slackbot:
       build: slackbot/
       volumes: 
       - ./slackbot/:/app     
       depends_on: 
       - pgdb       

        

